import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    anthropic: 'src/anthropic.ts',
    openai: 'src/openai.ts',
    xai: 'src/xai.ts',
    google: 'src/google.ts',
    'google/extras': 'src/google-extras.ts',
    voyage: 'src/voyage.ts',
    vertex: 'src/vertex.ts',
    image: 'src/image.ts',
    midjourney: 'src/midjourney.ts',
    yunwu: 'src/yunwu.ts',
    memory: 'src/memory.ts',
    'memory/markdown': 'src/memory-markdown.ts',
    pricing: 'src/pricing.ts',
    middleware: 'src/middleware.ts',
    rag: 'src/rag.ts',
    'rag/node': 'src/rag-node.ts',
    skills: 'src/skills.ts',
    'skills/node': 'src/skills/node.ts',
    'mcp/index': 'src/mcp/index.ts',
    'mcp/stdio': 'src/mcp/stdio.ts',
    edge: 'src/edge.ts',
    react: 'src/react.ts',
    ui: 'src/ui.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  clean: true,
  sourcemap: true,
  treeshake: true,
  splitting: true,
  target: 'es2022',
  outExtension({ format }) {
    return { js: format === 'cjs' ? '.cjs' : '.js' };
  },
});
