import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    index: 'src/index.ts',
    anthropic: 'src/anthropic.ts',
    openai: 'src/openai.ts',
    xai: 'src/xai.ts',
    google: 'src/google.ts',
    'google/extras': 'src/google-extras.ts',
    voyage: 'src/voyage.ts',
    azure: 'src/azure.ts',
    bedrock: 'src/bedrock.ts',
    vertex: 'src/vertex.ts',
    providers: 'src/providers.ts',
    testing: 'src/testing.ts',
    workspace: 'src/workspace.ts',
    'workspace/node': 'src/node/workspace.ts',
    compute: 'src/compute.ts',
    'compute/node': 'src/node/compute.ts',
    agent: 'src/agent.ts',
    swarm: 'src/swarm.ts',
    'swarm/sqlite': 'src/node/swarm-sqlite.ts',
    'swarm/postgres': 'src/node/swarm-postgres.ts',
    ops: 'src/ops.ts',
    'ops/sqlite': 'src/node/ops-sqlite.ts',
    'ops/postgres': 'src/node/ops-postgres.ts',
    evolve: 'src/evolve.ts',
    'evolve/sqlite': 'src/node/evolve-sqlite.ts',
    schedule: 'src/schedule.ts',
    autonomy: 'src/autonomy.ts',
    runtime: 'src/runtime.ts',
    'runtime/node': 'src/node/runtime.ts',
    browser: 'src/browser.ts',
    'browser/node': 'src/node/browser.ts',
    image: 'src/image.ts',
    speech: 'src/speech.ts',
    transcription: 'src/transcription.ts',
    video: 'src/video.ts',
    midjourney: 'src/midjourney.ts',
    yunwu: 'src/yunwu.ts',
    memory: 'src/memory.ts',
    'memory/markdown': 'src/memory-markdown.ts',
    pricing: 'src/pricing.ts',
    middleware: 'src/middleware.ts',
    guardrails: 'src/guardrails.ts',
    rag: 'src/rag.ts',
    'rag/node': 'src/rag-node.ts',
    skills: 'src/skills.ts',
    'skills/node': 'src/skills/node.ts',
    'mcp/index': 'src/mcp/index.ts',
    'mcp/stdio': 'src/mcp/stdio.ts',
    'mcp/node': 'src/node/mcp.ts',
    'stores/sqlite': 'src/node/store-sqlite.ts',
    'stores/redis': 'src/node/store-redis.ts',
    'stores/postgres': 'src/node/store-postgres.ts',
    durable: 'src/durable.ts',
    otel: 'src/otel.ts',
    observe: 'src/observe.ts',
    'observe/node': 'src/node/observe.ts',
    'vertex/node': 'src/node/vertex-auth.ts',
    edge: 'src/edge.ts',
    react: 'src/react.ts',
    ui: 'src/ui.ts',
    chat: 'src/chat.ts',
    'chat/node': 'src/node/chat-store.ts',
  },
  format: ['esm', 'cjs'],
  dts: true,
  clean: true,
  sourcemap: true,
  treeshake: true,
  splitting: true,
  target: 'es2022',
  outExtension({ format }) {
    return { js: format === 'cjs' ? '.cjs' : '.js' };
  },
});
